name: Nightly

on:
    schedule:
      - cron: '0 3 * * *'

jobs:
    nightly:
        name: Tests PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        continue-on-error: ${{ matrix.experimental }}
        strategy:
            fail-fast: false
            matrix:
                php: [8.2]
                experimental: [false]
                include:
                    - php: 8.2
                      analysis: true

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                ref: nightly

            - name: Git Push
              id: git
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git fetch origin
                git merge origin/master
                git push
